// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = HubspotFormSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *HubspotForm → Default → Primary*
 */
export interface HubspotFormSliceDefaultPrimary {
  /**
   * Form Id field in *HubspotForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hubspot_form.default.primary.form_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_id: prismic.KeyTextField;

  /**
   * Loader Type field in *HubspotForm → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hubspot_form.default.primary.loader_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  loader_type: prismic.SelectField<"1" | "2">;

  /**
   * Form Name field in *HubspotForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hubspot_form.default.primary.form_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_name: prismic.KeyTextField;

  /**
   * Form Confirmation Text field in *HubspotForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hubspot_form.default.primary.form_confirmation_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  form_confirmation_text: prismic.RichTextField;
}

/**
 * Default variation for HubspotForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HubspotFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HubspotFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HubspotForm*
 */
type HubspotFormSliceVariation = HubspotFormSliceDefault;

/**
 * HubspotForm Shared Slice
 *
 * - **API ID**: `hubspot_form`
 * - **Description**: HubspotForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HubspotFormSlice = prismic.SharedSlice<
  "hubspot_form",
  HubspotFormSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HubspotFormSlice,
      HubspotFormSliceDefaultPrimary,
      HubspotFormSliceVariation,
      HubspotFormSliceDefault,
    };
  }
}
